<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Mitra 1000s_card-img-rekom</name>
   <tag></tag>
   <elementGuidId>db38b6ac-9156-481d-afc6-36da46ba38f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='imgappend0']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#imgappend0 > img.card-img-rekom</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#imgappend0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9ed2f6c1-96dd-4f45-8e26-8a2e42260ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images-developer.1000saudara.com/assets/img/produk/original/thumb/thm_Papan-Semen-Dan-Aksesoris_O0Kilob0a0hRKmTUfDHU3vJXUjmyaRYN.jpeg</value>
      <webElementGuid>4df7d46e-6d14-4cfd-bff1-82b934145d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img-rekom</value>
      <webElementGuid>88201fef-1fb4-4a10-835e-383d6b7384f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7513ae6b-8f8f-4eb1-8415-446cd707c08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imgappend0&quot;)/img[@class=&quot;card-img-rekom&quot;]</value>
      <webElementGuid>78d6b458-d9a6-4a9b-8787-295421b018a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='imgappend0']/img</value>
      <webElementGuid>387a1455-dc7d-4232-a9dd-d2e0e4826bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://images-developer.1000saudara.com/assets/img/produk/original/thumb/thm_Papan-Semen-Dan-Aksesoris_O0Kilob0a0hRKmTUfDHU3vJXUjmyaRYN.jpeg')]</value>
      <webElementGuid>13cb6975-50dc-4b1a-a9e5-275302b630da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li/div/a/img</value>
      <webElementGuid>2f728192-b921-4a4e-a39b-80eb039d2f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://images-developer.1000saudara.com/assets/img/produk/original/thumb/thm_Papan-Semen-Dan-Aksesoris_O0Kilob0a0hRKmTUfDHU3vJXUjmyaRYN.jpeg']</value>
      <webElementGuid>977e9540-dd1f-4ee6-ab82-9d57232246c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
